version: '3.8'
services:
  app:
    container_name: backend
    build:                        
      context: ./backend          
      dockerfile: Dockerfile       
    volumes:
      - ./backend:/app 
    depends_on:
      - postgres
      - nats 
    env_file:
      - .env  
    ports:
      - "3002:3002"  
    networks:
      - my-network

  postgres:
    container_name: postgres
    build:                        
      context: ./dbs/postgres              
      dockerfile: Dockerfile    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env   
    ports:
      - "5433:5432"
    networks:
      - my-network 
            
networks:
  my-network:

volumes:
  postgres_data:
  mysql_data:
