#!/bin/bash

psql --username "$POSTGRES_USER" <<EOF
CREATE DATABASE "$POSTGRES_DB";

CREATE USER "$POSTGRES_USER" WITH PASSWORD '$POSTGRES_PASSWORD';

GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_USER";

GRANT USAGE ON SCHEMA public TO "$POSTGRES_USER";
EOF
